### ISSUE TITLE
Add Resistance 204X

### ISSUE THREAD

**Issue by chulini** [AndreaJens/indie-fighting-game-ads#1]
Thanks Andrea! ✌️ 
![Reistance204X](https://github.com/AndreaJens/indie-fighting-game-ads/assets/1395214/889c223c-5ba2-4947-be78-df0576ef3924)

**Comment by AndreaJens** [comment]
Uploaded in commit 81bcd9498a47a5afb4d2624ffdf6b879aa5f8055 :) Thanks for your patience!
